In [1]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "I love programming in Python",
    "Python is great for machine learning",
    "I love machine learning"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

print(X.toarray())
print(vectorizer.get_feature_names_out())


[[0 0 1 0 0 1 0 1 1]
 [1 1 0 1 1 0 1 0 1]
 [0 0 0 0 1 1 1 0 0]]
['for' 'great' 'in' 'is' 'learning' 'love' 'machine' 'programming'
 'python']


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import warnings 
warnings.filterwarnings('ignore')

In [3]:
data = {
    "Email": [
        "Congratulations! You've won a free iPhone. Click here to claim now.",
        "Meeting scheduled for 3 PM today. Please confirm your availability.",
        "Get rich quick! Earn $5000 per day from home. Sign up now!",
        "Your Amazon order has been shipped. Track your package here.",
        "Exclusive offer! 50% off on all products. Limited time only.",
        "Hi John, can you send me the project report by tomorrow?"
    ],
    "Spam": [1, 0, 1, 0, 1, 0]
}

In [4]:
df = pd.DataFrame(data)
df

Email  Spam
0  Congratulations! You've won a free iPhone. Cli...     1
1  Meeting scheduled for 3 PM today. Please confi...     0
2  Get rich quick! Earn $5000 per day from home. ...     1
3  Your Amazon order has been shipped. Track your...     0
4  Exclusive offer! 50% off on all products. Limi...     1
5  Hi John, can you send me the project report by...     0

In [5]:
vectorize = CountVectorizer()
X = vectorize.fit_transform(df['Email'])

In [6]:
y = df['Spam']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
svm_model = SVC(kernel="linear")

In [9]:
svm_model.fit(X_train,y_train)

SVC(kernel='linear')

In [10]:
y_pred = svm_model.predict(X_test)
y_pred

array([0, 0])

In [11]:
print(accuracy_score(y_test,y_pred))

0.5


In [12]:
# with real Dataset

In [13]:
iris_data = pd.read_excel("Files/iris_data.xlsx")
iris_data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [14]:
X = iris_data.drop(columns="species")
y = iris_data[['species']]

In [15]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
model = SVC(kernel="linear")

In [17]:
model.fit(X_train1,y_train1)

SVC(kernel='linear')

In [18]:
y_pred1 = model.predict(X_test1)
y_pred1

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa'], dtype=object)

In [19]:
print(accuracy_score(y_test1,y_pred1))

1.0
